services:
  router:
    build: ./router
    container_name: router
    networks:
      production:
        ipv4_address: 172.30.0.2
      development:
        ipv4_address: 172.40.0.2
      service:
        ipv4_address: 172.20.0.2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  prod_container:
    build: ./prod-container
    container_name: prod_container
    networks:
      production:
    cap_add:
      - NET_ADMIN
    dns:
      - 172.30.0.2
    depends_on:
      - router
      - dns_server
    restart: unless-stopped

  dev_container:
    build: ./dev-container
    container_name: dev_container
    networks:
      development:
    cap_add:
      - NET_ADMIN
    dns:
      - 172.20.0.100
    depends_on:
      - router
      - dns_server
    restart: unless-stopped

  dns_server:
    build: ./dns_debian
    container_name: dns_server
    networks:
      service:
        ipv4_address: 172.20.0.100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  production:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
  development:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24
  service:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24