FROM mysql:8

# Instalar herramientas de red
RUN microdnf update -y && microdnf install -y iproute iputils

# Crear script de inicio personalizado
COPY mysql-entrypoint.sh /mysql-entrypoint.sh
RUN chmod +x /mysql-entrypoint.sh

ENTRYPOINT ["/mysql-entrypoint.sh"]
CMD ["mysqld"]